trigger:
  branches:
    include:
      - main  # Cambia esto a la rama que desees monitorear

variables:
  azureContainerAppName: 'crowd-watch-rtm-app'  # Nombre de tu Azure Container App
  resourceGroup: 'crowd-watch-test-resource-group'  # Grupo de recursos donde está el Container App
  azureSuscription: 'dff67055-79ce-4d29-9331-5375c531cba3'

stages:
  - stage: Build_and_Test
    displayName: 'Build and Run Tests'
    jobs:
      - job: Build
        displayName: 'Compile Quarkus Microservice and update image'
        steps:
          - script: |
              echo "Verificando versión de Java..."
              java --version
              echo "JAVA_HOME: $JAVA_HOME"
              which java
            displayName: 'Verificar Java Instalado' 

          - task: AzureCLI@2
            inputs:
              azureSubscription: $(azureSuscription)
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                set -x
                az acr login --name crowdwatchregistry
                
          - script: |
              mvn clean package
            env:
              RTM_VERSION: '1.0'
            displayName: 'Build Quarkus Project'

  - stage: Deploy_to_Azure_Container_App
    displayName: 'Deploy to Azure Container App'
    dependsOn: Build_and_Test
    jobs:
      - job: Deploy
        displayName: 'Update Azure Container App Image'
        steps:
          - task: AzurePowerShell@5
            inputs:
              azureSubscription: $(azureSuscription)
              ScriptType: 'InlineScript'
              Inline: |
                Write-Host "Intentando detener la Container App..."
                Stop-AzContainerApp -Name $(azureContainerAppName) -ResourceGroupName $(resourceGroup)
                Write-Host "Intentando iniciar la Container App..."
                Start-AzContainerApp -Name $(azureContainerAppName) -ResourceGroupName $(resourceGroup)
              azurePowerShellVersion: LatestVersion